ex2:
	gcc -std=c99 -Wall -Wextra node.c ex2.c functions.c function_pointers.c -o ex2
fptest:
	gcc -std=c99 -Wall -Wextra node.c ex2.c functions.c function_pointers.c -o fptest

clean:
	rm -f *.o ex2 fptest
